Repository AY2021S2-CS2103T-W10-2/tp, pull requests merged in 2021-04, with the labels that each got.

#207 Update Index.md
  docs/index.md
Labels: priority.High, severity.Low, type.Bug

#212 Hotfix index.md
  docs/index.md
Labels: priority.High, severity.Medium, type.Bug

#217 Update on UG v3 Kumaran
  docs/UserGuide.md
Labels: priority.High, severity.Medium, type.Chore

#219 make breaklines between sections work
  docs/UserGuide.md
Labels: priority.High, severity.Medium, type.Chore

#216 Add location list panel to GUI
  docs/index.md
  src/main/java/seedu/storemando/logic/Logic.java
  src/main/java/seedu/storemando/logic/LogicManager.java
  src/main/java/seedu/storemando/model/Model.java
  src/main/java/seedu/storemando/model/ModelManager.java
  src/main/java/seedu/storemando/model/ReadOnlyStoreMando.java
  src/main/java/seedu/storemando/model/StoreMando.java
  src/main/java/seedu/storemando/ui/LocationCard.java
  src/main/java/seedu/storemando/ui/LocationListPanel.java
  src/main/java/seedu/storemando/ui/MainWindow.java
  src/main/resources/view/LocationListCard.fxml
  src/main/resources/view/LocationListPanel.fxml
  src/main/resources/view/MainTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/storemando/logic/commands/AddCommandTest.java
  src/test/java/seedu/storemando/model/StoreMandoTest.java
Labels: priority.Medium, severity.Low, type.Enhancement

#215 Add Expiring Items table to main window
  docs/UserGuide.md
  src/main/java/seedu/storemando/ui/MainWindow.java
  src/main/java/seedu/storemando/ui/TablePanel.java
  src/main/resources/view/MainTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TablePanel.fxml
Labels: priority.Medium, severity.High, type.Enhancement

#265 Feature CSS Amanda
  src/main/java/seedu/storemando/ui/ItemCard.java
  src/main/resources/view/MainTheme.css
Labels: priority.Medium, severity.Medium, type.Enhancement

#263 Update Kumaran Markdown
  docs/team/kumaran.md
Labels: priority.High, severity.VeryLow, type.Chore

#221 DG Implementation Reminder and Clear
  docs/DeveloperGuide.md
  docs/diagrams/ClearLocationActivityDiagram.puml
  docs/diagrams/ClearLocationSequenceDiagram.puml
  docs/diagrams/ClearSequenceDiagram.puml
  docs/diagrams/ReminderActivityDiagram.puml
  docs/diagrams/ReminderDaysSequenceDiagram.puml
  docs/diagrams/ReminderWeeksSequenceDiagram.puml
  docs/images/ClearLocationActivityDiagram.png
  docs/images/ClearLocationSequenceDiagram.png
  docs/images/ClearSequenceDiagram.png
  docs/images/ReminderActivityDiagram.png
  docs/images/ReminderDaysSequenceDiagram.png
  docs/images/ReminderWeeksSequenceDiagram.png
Labels: priority.High, severity.Medium, type.Chore

#204 Markdown file Jay
  docs/team/jaychenyj.md
Labels: priority.High, severity.Low, type.Chore

#211 DG Implementation Delete
  docs/DeveloperGuide.md
  docs/diagrams/DeleteActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/DeleteActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
Labels: priority.High, severity.Medium, type.Chore

#213 DG Implementation List and Find
  docs/DeveloperGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/FindFullSequenceDiagram.puml
  docs/diagrams/FindPartialSequenceDiagram.puml
  docs/diagrams/ListActivityDiagram.puml
  docs/diagrams/ListLocationSequenceDiagram.puml
  docs/diagrams/ListStoreMandoSequenceDiagram.puml
  docs/images/CommitActivityDiagram.png
  docs/images/FindActivityDiagram.png
  docs/images/FindFullSequenceDiagram.png
  docs/images/FindPartialSequenceDiagram.png
  docs/images/ListActivityDiagram.png
  docs/images/ListLocationSequenceDiagram.png
  docs/images/ListStoreMandoSequenceDiagram.png
Labels: priority.High, severity.Medium, type.Chore

#222 Update Fazil Markdown
  docs/team/mohamedfazil.md
Labels: priority.High, severity.VeryLow, type.Chore

#220 DG Implementation Add and Sort
  docs/DeveloperGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/SortActivityDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/AddActivityDiagram.png
  docs/images/AddSequenceDiagram.png
  docs/images/SortActivityDiagram.png
  docs/images/SortSequenceDiagram.png
Labels: priority.High, severity.Medium, type.Chore

#270 Update Markdown Files
  docs/AboutUs.md
  docs/SettingUp.md
  docs/index.md
Labels: priority.High, severity.Low, type.Chore

#271 Update documentation Jay
  docs/Configuration.md
  docs/DevOps.md
  docs/Documentation.md
  docs/Testing.md
Labels: priority.High, severity.Low, type.Chore

#267 Updated markdown file Amanda
  docs/team/amandaang.md
Labels: priority.High, severity.VeryLow, type.Chore

#214 DG Implemetation Edit and Help
  docs/DeveloperGuide.md
  docs/diagrams/EditActivityDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/HelpActivityDiagram.puml
  docs/diagrams/HelpSequenceDiagram.puml
  docs/images/EditActivityDiagram.png
  docs/images/EditSequenceDiagram.png
  docs/images/HelpActivityDiagram.png
  docs/images/HelpSequenceDiagram.png
Labels: priority.High, severity.VeryLow, type.Chore

#266 Update WeiHao Markdown.
  docs/team/chewwh09.md
Labels: priority.High, severity.VeryLow, type.Chore

#272 Change storing of quantity value to remove leading zeroes
  src/main/java/seedu/storemando/model/item/Quantity.java
Labels: priority.High, severity.Medium, type.Bug

#273 Fix bug regarding quantity max integer
  docs/UserGuide.md
  src/main/java/seedu/storemando/model/item/Quantity.java
  src/test/java/seedu/storemando/model/item/QuantityTest.java
  src/test/java/seedu/storemando/testutil/ItemBuilder.java
Labels: priority.Medium, severity.Low, type.Bug

#281 Gui styling
  src/main/resources/view/MainTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, severity.High, type.Enhancement

#274 Add maximum and minimum integer limits for Reminder
  docs/UserGuide.md
  src/main/java/seedu/storemando/logic/commands/ReminderCommand.java
  src/main/java/seedu/storemando/logic/parser/ReminderCommandParser.java
  src/test/java/seedu/storemando/logic/parser/ReminderCommandParserTest.java
Labels: priority.High, severity.Low, type.Bug

#283 GUI Enhancement
  src/main/java/seedu/storemando/logic/Logic.java
  src/main/java/seedu/storemando/logic/LogicManager.java
  src/main/java/seedu/storemando/model/Model.java
  src/main/java/seedu/storemando/model/ModelManager.java
  src/main/java/seedu/storemando/model/ReadOnlyStoreMando.java
  src/main/java/seedu/storemando/model/StoreMando.java
  src/main/java/seedu/storemando/ui/ItemCard.java
  src/main/java/seedu/storemando/ui/LocationCard.java
  src/main/java/seedu/storemando/ui/LocationListPanel.java
  src/main/java/seedu/storemando/ui/MainWindow.java
  src/main/java/seedu/storemando/ui/TablePanel.java
  src/main/resources/view/LocationListCard.fxml
  src/main/resources/view/LocationListPanel.fxml
  src/main/resources/view/MainTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TablePanel.fxml
  src/test/java/seedu/storemando/logic/commands/AddCommandTest.java
  src/test/java/seedu/storemando/model/StoreMandoTest.java
Labels: priority.Medium, severity.High, type.Enhancement

#284 Rename PPP File Names
  docs/AboutUs.md
  docs/team/github-amanda.md
  docs/team/kumsssss.md
  docs/team/md-fazil.md
Labels: priority.High, severity.High, type.Bug, type.Chore

#279 Update DG apart from Implementation Jay
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/LogicClassDiagram.png
Labels: priority.High, severity.Medium, type.Chore

#286 Hotfix for expiry date of typical items
  src/test/data/JsonSerializableStoreMandoTest/typicalItemsStoreMando.json
  src/test/java/seedu/storemando/logic/commands/ReminderCommandTest.java
  src/test/java/seedu/storemando/model/item/ItemComparatorByExpiryDateTest.java
  src/test/java/seedu/storemando/testutil/TypicalItems.java
Labels: priority.High, severity.Low, type.Bug

#282 Chore message
  src/main/java/seedu/storemando/logic/commands/ListCommand.java
  src/main/java/seedu/storemando/logic/commands/ReminderCommand.java
  src/main/java/seedu/storemando/logic/commands/SortAscendingQuantityCommand.java
  src/main/java/seedu/storemando/logic/commands/SortCommand.java
  src/main/java/seedu/storemando/logic/commands/SortDescendingQuantityCommand.java
  src/main/java/seedu/storemando/logic/commands/SortExpiryDateCommand.java
  src/main/java/seedu/storemando/logic/parser/ListCommandParser.java
  src/main/java/seedu/storemando/logic/parser/ReminderCommandParser.java
  src/main/java/seedu/storemando/model/tag/Tag.java
  src/test/java/seedu/storemando/logic/commands/ListCommandTest.java
  src/test/java/seedu/storemando/logic/commands/ReminderCommandTest.java
  src/test/java/seedu/storemando/logic/commands/SortAscendingQuantityCommandTest.java
  src/test/java/seedu/storemando/logic/commands/SortDescendingQuantityCommandTest.java
  src/test/java/seedu/storemando/logic/commands/SortExpiryDateCommandTest.java
  src/test/java/seedu/storemando/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/ReminderCommandParserTest.java
Labels: priority.Medium, severity.Low, type.Chore

#285 Update DG user stories, use cases, glossary and NFR Amanda
  docs/DeveloperGuide.md
Labels: priority.High, severity.Medium, type.Chore

#291 Test commons core
  src/test/java/seedu/storemando/commons/core/ConfigTest.java
  src/test/java/seedu/storemando/commons/core/VersionTest.java
Labels: priority.High, severity.Medium, type.Chore

#290 Fix FindCommandParser bug
  src/main/java/seedu/storemando/logic/parser/FindCommandParser.java
Labels: priority.Medium, severity.Low, type.Enhancement

#294 Update List and Find Activity Diagrams
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/ListActivityDiagram.puml
  docs/images/FindActivityDiagram.png
  docs/images/ListActivityDiagram.png
Labels: priority.High, severity.Medium, type.Chore

#292 Update test logic
  src/main/java/seedu/storemando/logic/parser/ClearCommandParser.java
  src/test/java/seedu/storemando/logic/LogicManagerTest.java
  src/test/java/seedu/storemando/logic/commands/ClearCommandTest.java
  src/test/java/seedu/storemando/logic/parser/ClearCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/ReminderCommandParserTest.java
Labels: priority.High, severity.Medium, type.Chore

#288 Standardise DG implementation
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
  docs/diagrams/ReminderDaysSequenceDiagram.puml
  docs/diagrams/ReminderWeeksSequenceDiagram.puml
  docs/images/AddSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ListSequenceDiagram.png
  docs/images/ReminderDaysSequenceDiagram.png
  docs/images/ReminderWeeksSequenceDiagram.png
Labels: priority.High, severity.Medium, type.Chore

#289 Update doc dg implementation
  docs/DeveloperGuide.md
  docs/diagrams/ClearLocationSequenceDiagram.puml
  docs/diagrams/ClearSequenceDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/FindFullSequenceDiagram.puml
  docs/diagrams/FindPartialSequenceDiagram.puml
  docs/diagrams/HelpSequenceDiagram.puml
  docs/images/ClearLocationSequenceDiagram.png
  docs/images/ClearSequenceDiagram.png
  docs/images/EditSequenceDiagram.png
  docs/images/FindFullSequenceDiagram.png
  docs/images/FindPartialSequenceDiagram.png
  docs/images/HelpSequenceDiagram.png
  docs/images/SortSequenceDiagram.png
Labels: priority.High, severity.Medium, type.Chore

#302 Update DG implementation layout
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, severity.Low, type.Chore

#303 Throw error message on filtering commands when list is empty
  src/main/java/seedu/storemando/commons/core/Messages.java
  src/main/java/seedu/storemando/logic/commands/ClearCommand.java
  src/main/java/seedu/storemando/logic/commands/FindCommand.java
  src/main/java/seedu/storemando/logic/commands/ListCommand.java
  src/main/java/seedu/storemando/logic/commands/ReminderCommand.java
  src/main/java/seedu/storemando/logic/commands/SortAscendingQuantityCommand.java
  src/main/java/seedu/storemando/logic/commands/SortCommand.java
  src/main/java/seedu/storemando/logic/commands/SortDescendingQuantityCommand.java
  src/main/java/seedu/storemando/logic/commands/SortExpiryDateCommand.java
  src/test/java/seedu/storemando/logic/commands/ClearCommandTest.java
  src/test/java/seedu/storemando/logic/commands/FindCommandTest.java
  src/test/java/seedu/storemando/logic/commands/ListCommandTest.java
  src/test/java/seedu/storemando/logic/commands/ReminderCommandTest.java
  src/test/java/seedu/storemando/logic/commands/SortAscendingQuantityCommandTest.java
  src/test/java/seedu/storemando/logic/commands/SortDescendingQuantityCommandTest.java
  src/test/java/seedu/storemando/logic/commands/SortExpiryDateCommandTest.java
Labels: priority.High, severity.Medium, type.Enhancement

#308 Add effort section in Developer Guide
  docs/DeveloperGuide.md
Labels: priority.High, severity.Medium, type.Chore

#305 Test improve coverage
  src/main/java/seedu/storemando/logic/commands/ReminderCommand.java
  src/test/java/seedu/storemando/logic/commands/ReminderCommandTest.java
  src/test/java/seedu/storemando/model/StoreMandoTest.java
  src/test/java/seedu/storemando/model/item/LocationContainsPredicateTest.java
Labels: priority.Medium, severity.Low, type.Chore

#312 Update Developer Guide and User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, severity.Medium, type.Enhancement

#315 Fix ReminderCommandParser bug
  src/main/java/seedu/storemando/logic/parser/ReminderCommandParser.java
  src/test/java/seedu/storemando/logic/parser/ReminderCommandParserTest.java
Labels: priority.Medium, severity.Low, type.Enhancement

#313 Standardise command format message
  src/main/java/seedu/storemando/commons/core/Messages.java
  src/main/java/seedu/storemando/logic/commands/AddCommand.java
  src/main/java/seedu/storemando/logic/commands/ClearCommand.java
  src/main/java/seedu/storemando/logic/commands/FindCommand.java
  src/main/java/seedu/storemando/logic/commands/ListCommand.java
  src/main/java/seedu/storemando/logic/commands/ReminderCommand.java
  src/main/java/seedu/storemando/logic/commands/SortCommand.java
  src/test/java/seedu/storemando/commons/core/MessagesTest.java
  src/test/java/seedu/storemando/logic/commands/FindCommandTest.java
Labels: priority.Medium, severity.Low, type.Enhancement

#304 Gui table expired item
  src/main/java/seedu/storemando/logic/Logic.java
  src/main/java/seedu/storemando/logic/LogicManager.java
  src/main/java/seedu/storemando/model/Model.java
  src/main/java/seedu/storemando/model/ModelManager.java
  src/main/java/seedu/storemando/ui/ExpiredTablePanel.java
  src/main/java/seedu/storemando/ui/ExpiringTablePanel.java
  src/main/java/seedu/storemando/ui/MainWindow.java
  src/main/resources/view/MainTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/TablePanel.fxml
  src/test/java/seedu/storemando/logic/LogicManagerTest.java
  src/test/java/seedu/storemando/logic/commands/AddCommandTest.java
  src/test/java/seedu/storemando/model/ModelManagerTest.java
Labels: priority.Medium, severity.High, type.Enhancement

#316 Update UG Documentation
  docs/UserGuide.md
Labels: priority.Medium, severity.Low, type.Chore

#319 Split ClearCommand classes into two subclasses and ClearCommandTest c…
  src/main/java/seedu/storemando/logic/commands/ClearAllCommand.java
  src/main/java/seedu/storemando/logic/commands/ClearCommand.java
  src/main/java/seedu/storemando/logic/commands/ClearLocationCommand.java
  src/main/java/seedu/storemando/logic/parser/ClearCommandParser.java
  src/test/java/seedu/storemando/logic/commands/ClearAllCommandTest.java
  src/test/java/seedu/storemando/logic/commands/ClearLocationCommandTest.java
  src/test/java/seedu/storemando/logic/commands/EditCommandTest.java
  src/test/java/seedu/storemando/logic/parser/ClearCommandParserTest.java
Labels: priority.Medium, severity.Low, type.Enhancement

#320 Update User Guide Layout Section
  docs/UserGuide.md
Labels: priority.High, severity.High, type.Chore

#322 Update UiClassDiagram
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: priority.High, severity.Low, type.Chore

#321 UG Update Final Jay
  docs/UserGuide.md
  docs/images/SeEduLogo.png
  docs/images/Ui.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  docs/images/request_access.png
Labels: priority.High, severity.Medium, type.Chore

#323 Gui refinement
  src/main/java/seedu/storemando/ui/ExpiredTablePanel.java
  src/main/java/seedu/storemando/ui/ExpiringTablePanel.java
  src/main/resources/view/MainTheme.css
  src/main/resources/view/TablePanel.fxml
Labels: priority.Medium, severity.Low, type.Enhancement

#324 Repackage classes
  docs/UserGuide.md
  docs/images/GUILayout.png
  docs/images/Ui.png
  src/main/java/seedu/storemando/logic/commands/ClearLocationCommand.java
  src/main/java/seedu/storemando/logic/commands/FindCommand.java
  src/main/java/seedu/storemando/logic/commands/ListCommand.java
  src/main/java/seedu/storemando/logic/commands/ReminderCommand.java
  src/main/java/seedu/storemando/logic/commands/SortAscendingQuantityCommand.java
  src/main/java/seedu/storemando/logic/commands/SortDescendingQuantityCommand.java
  src/main/java/seedu/storemando/logic/commands/SortExpiryDateCommand.java
  src/main/java/seedu/storemando/logic/parser/ClearCommandParser.java
  src/main/java/seedu/storemando/logic/parser/FindCommandParser.java
  src/main/java/seedu/storemando/logic/parser/ListCommandParser.java
  src/main/java/seedu/storemando/logic/parser/ReminderCommandParser.java
  src/main/java/seedu/storemando/model/expirydate/predicate/ItemExpiringPredicate.java
  src/main/java/seedu/storemando/model/item/comparator/ItemComparatorByDecreasingQuantity.java
  src/main/java/seedu/storemando/model/item/comparator/ItemComparatorByExpiryDate.java
  src/main/java/seedu/storemando/model/item/comparator/ItemComparatorByIncreasingQuantity.java
  src/main/java/seedu/storemando/model/item/predicate/ItemNameContainsKeywordsPredicate.java
  src/main/java/seedu/storemando/model/item/predicate/ItemNameContainsPartialKeywordsPredicate.java
  src/main/java/seedu/storemando/model/item/predicate/LocationContainsKeywordsPredicate.java
  src/main/java/seedu/storemando/model/item/predicate/LocationContainsPredicate.java
  src/main/java/seedu/storemando/model/tag/predicate/TagContainsKeywordsPredicate.java
  src/main/java/seedu/storemando/ui/ItemCard.java
  src/test/java/seedu/storemando/logic/commands/ClearAllCommandTest.java
  src/test/java/seedu/storemando/logic/commands/ClearLocationCommandTest.java
  src/test/java/seedu/storemando/logic/commands/CommandTestUtil.java
  src/test/java/seedu/storemando/logic/commands/FindCommandTest.java
  src/test/java/seedu/storemando/logic/commands/ListCommandTest.java
  src/test/java/seedu/storemando/logic/commands/ReminderCommandTest.java
  src/test/java/seedu/storemando/logic/parser/ClearCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/ReminderCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/StoreMandoParserTest.java
  src/test/java/seedu/storemando/model/ModelManagerTest.java
  src/test/java/seedu/storemando/model/item/ItemComparatorByDecreasingQuantityTest.java
  src/test/java/seedu/storemando/model/item/ItemComparatorByExpiryDateTest.java
  src/test/java/seedu/storemando/model/item/ItemComparatorByQuantityTest.java
  src/test/java/seedu/storemando/model/item/ItemExpiringPredicateTest.java
  src/test/java/seedu/storemando/model/item/ItemNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/storemando/model/item/ItemNameContainsPartialKeywordsPredicateTest.java
  src/test/java/seedu/storemando/model/item/LocationContainsKeywordsPredicateTest.java
  src/test/java/seedu/storemando/model/item/LocationContainsPredicateTest.java
  src/test/java/seedu/storemando/model/tag/TagContainsKeywordsPredicateTest.java
Labels: priority.Medium, severity.Low, type.Enhancement

#327 Update DG Documentation
  docs/DeveloperGuide.md
Labels: priority.Medium, severity.Medium, type.Chore

#328 Add tests
  src/test/java/seedu/storemando/commons/core/MessagesTest.java
  src/test/java/seedu/storemando/logic/commands/EditCommandTest.java
  src/test/java/seedu/storemando/logic/commands/ReminderCommandTest.java
  src/test/java/seedu/storemando/model/UserPrefsTest.java
  src/test/java/seedu/storemando/model/item/QuantityTest.java
Labels: priority.Medium, severity.Low, type.Chore

#326 Modify DG use cases Amanda
  docs/DeveloperGuide.md
Labels: priority.Medium, severity.Low, type.Chore

#332 Standardise messages in command classes
  src/main/java/seedu/storemando/logic/commands/AddCommand.java
  src/main/java/seedu/storemando/logic/commands/ClearCommand.java
  src/main/java/seedu/storemando/logic/commands/DeleteCommand.java
  src/main/java/seedu/storemando/logic/commands/EditCommand.java
  src/main/java/seedu/storemando/logic/commands/ExitCommand.java
  src/main/java/seedu/storemando/logic/commands/ListCommand.java
  src/main/java/seedu/storemando/logic/commands/ReminderCommand.java
  src/main/java/seedu/storemando/logic/commands/SortCommand.java
  src/main/java/seedu/storemando/logic/commands/SortExpiryDateCommand.java
Labels: priority.Medium, severity.Low, type.Enhancement

#330 UG Layout
  docs/UserGuide.md
Labels: priority.Medium, severity.Low, type.Chore

#334 Add Javadoc comments
  src/main/java/seedu/storemando/logic/Logic.java
  src/main/java/seedu/storemando/logic/parser/AddCommandParser.java
  src/main/java/seedu/storemando/logic/parser/ClearCommandParser.java
  src/main/java/seedu/storemando/logic/parser/CliSyntax.java
  src/main/java/seedu/storemando/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/storemando/logic/parser/EditCommandParser.java
  src/main/java/seedu/storemando/logic/parser/FindCommandParser.java
  src/main/java/seedu/storemando/logic/parser/ListCommandParser.java
  src/main/java/seedu/storemando/logic/parser/ReminderCommandParser.java
  src/main/java/seedu/storemando/logic/parser/SortCommandParser.java
  src/main/java/seedu/storemando/logic/parser/StoreMandoParser.java
  src/main/java/seedu/storemando/model/Model.java
  src/main/java/seedu/storemando/model/StoreMando.java
  src/main/java/seedu/storemando/model/expirydate/ExpiryDate.java
  src/main/java/seedu/storemando/model/tag/Tag.java
  src/main/java/seedu/storemando/model/tag/predicate/TagContainsKeywordsPredicate.java
Labels: priority.High, severity.VeryLow, type.Chore

#335 Add javadocs
  src/main/java/seedu/storemando/logic/commands/AddCommand.java
  src/main/java/seedu/storemando/logic/commands/ClearAllCommand.java
  src/main/java/seedu/storemando/logic/commands/ClearLocationCommand.java
  src/main/java/seedu/storemando/logic/commands/Command.java
  src/main/java/seedu/storemando/logic/commands/DeleteCommand.java
  src/main/java/seedu/storemando/logic/commands/EditCommand.java
  src/main/java/seedu/storemando/logic/commands/FindCommand.java
  src/main/java/seedu/storemando/logic/commands/ListCommand.java
  src/main/java/seedu/storemando/logic/commands/ReminderCommand.java
  src/main/java/seedu/storemando/logic/commands/SortAscendingQuantityCommand.java
  src/main/java/seedu/storemando/logic/commands/SortDescendingQuantityCommand.java
  src/main/java/seedu/storemando/logic/commands/SortExpiryDateCommand.java
  src/main/java/seedu/storemando/model/item/Item.java
  src/main/java/seedu/storemando/model/item/ItemName.java
  src/main/java/seedu/storemando/model/item/Location.java
  src/main/java/seedu/storemando/model/item/Quantity.java
  src/main/java/seedu/storemando/model/item/comparator/ItemComparatorByDecreasingQuantity.java
  src/main/java/seedu/storemando/model/item/comparator/ItemComparatorByExpiryDate.java
  src/main/java/seedu/storemando/model/item/comparator/ItemComparatorByIncreasingQuantity.java
  src/main/java/seedu/storemando/model/item/predicate/ItemNameContainsKeywordsPredicate.java
  src/main/java/seedu/storemando/model/item/predicate/ItemNameContainsPartialKeywordsPredicate.java
  src/main/java/seedu/storemando/model/item/predicate/LocationContainsKeywordsPredicate.java
  src/main/java/seedu/storemando/model/item/predicate/LocationContainsPredicate.java
  src/main/java/seedu/storemando/ui/ExpiredTablePanel.java
  src/main/java/seedu/storemando/ui/ExpiringTablePanel.java
  src/main/java/seedu/storemando/ui/HelpWindow.java
  src/main/java/seedu/storemando/ui/ItemCard.java
  src/main/java/seedu/storemando/ui/MainWindow.java
  src/main/java/seedu/storemando/ui/Ui.java
Labels: priority.Medium, severity.VeryLow, type.Chore

#333 DG Layout
  docs/DeveloperGuide.md
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/FindFullSequenceDiagram.png
  docs/images/FindPartialSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/findAlexDavidResult.png
Labels: priority.Medium, severity.Low, type.Chore

#339 Final PPP Jay
  docs/team/jaychenyj.md
Labels: priority.High, severity.Medium, type.Chore

#337 Update Amanda Markdown
  docs/team/github-amanda.md
Labels: priority.High, severity.VeryLow, type.Chore

#340 Update Fazil PPP
  docs/team/md-fazil.md
Labels: priority.High, severity.High, type.Chore

#341 Doc ppp weihao
  docs/team/chewwh09.md
  docs/team/kumsssss.md
Labels: priority.High, severity.Low, type.Chore
