Repository AY2021S2-CS2103T-W10-2/tp, pull requests merged in 2021-03, with the labels that each got.

#56 Refactor email to expirydate
  docs/tutorials/RemovingFields.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/item/ExpiryDate.java
  src/main/java/seedu/address/model/item/Item.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedItem.java
  src/main/java/seedu/address/ui/ItemCard.java
  src/main/resources/view/ItemListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidItemAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateItemAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidItemAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalItemsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditItemDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/item/EmailTest.java
  src/test/java/seedu/address/model/item/ExpiryDateTest.java
  src/test/java/seedu/address/model/item/ItemTest.java
  src/test/java/seedu/address/model/item/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedItemTest.java
  src/test/java/seedu/address/testutil/EditItemDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ItemBuilder.java
  src/test/java/seedu/address/testutil/ItemUtil.java
  src/test/java/seedu/address/testutil/TypicalItems.java
Labels: refactor

#53 Refactor Name to ItemName
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/item/Item.java
  src/main/java/seedu/address/model/item/ItemName.java
  src/main/java/seedu/address/model/item/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedItem.java
  src/main/java/seedu/address/ui/ItemCard.java
  src/test/data/JsonAddressBookStorageTest/invalidItemAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/item/NameTest.java
  src/test/java/seedu/address/storage/JsonAdaptedItemTest.java
  src/test/java/seedu/address/testutil/EditItemDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ItemBuilder.java
  src/test/java/seedu/address/testutil/ItemUtil.java
  src/test/java/seedu/address/ui/TestFxmlObject.java
  src/test/resources/view/UiPartTest/validFileWithFxRoot.fxml
Labels: priority.High, refactor, type.Chore

#54 Refactor phone to quantity
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/item/Item.java
  src/main/java/seedu/address/model/item/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/item/Phone.java
  src/main/java/seedu/address/model/item/Quantity.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedItem.java
  src/main/java/seedu/address/ui/ItemCard.java
  src/main/resources/view/ItemListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidItemAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidItemAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateItemAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidItemAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalItemsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditItemDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/item/ItemTest.java
  src/test/java/seedu/address/model/item/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/item/PhoneTest.java
  src/test/java/seedu/address/model/item/QuantityTest.java
  src/test/java/seedu/address/storage/JsonAdaptedItemTest.java
  src/test/java/seedu/address/testutil/EditItemDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ItemBuilder.java
  src/test/java/seedu/address/testutil/ItemUtil.java
  src/test/java/seedu/address/testutil/TypicalItems.java
Labels: priority.High, type.Chore

#72 Refactor minor changes
  src/main/java/seedu/storemando/commons/core/Messages.java
  src/main/java/seedu/storemando/logic/commands/EditCommand.java
  src/main/java/seedu/storemando/logic/commands/FindCommand.java
  src/main/java/seedu/storemando/logic/commands/ListCommand.java
  src/main/java/seedu/storemando/model/StoreMando.java
  src/main/java/seedu/storemando/model/item/ItemName.java
  src/main/java/seedu/storemando/model/item/Location.java
  src/main/java/seedu/storemando/ui/ItemCard.java
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonSerializableStoreMandoTest/invalidItemStoreMando.json
  src/test/data/JsonStoreMandoStorageTest/invalidItemStoreMando.json
  src/test/java/seedu/storemando/commons/core/index/IndexTest.java
  src/test/java/seedu/storemando/logic/commands/EditItemDescriptorTest.java
  src/test/java/seedu/storemando/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/storemando/model/item/ExpiryDateTest.java
  src/test/java/seedu/storemando/model/item/ItemTest.java
  src/test/java/seedu/storemando/model/item/LocationTest.java
  src/test/java/seedu/storemando/model/item/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/storemando/testutil/EditItemDescriptorBuilder.java
  src/test/java/seedu/storemando/testutil/ItemBuilder.java
  src/test/java/seedu/storemando/testutil/ItemUtil.java
  src/test/java/seedu/storemando/testutil/StoreMandoBuilder.java
Labels: priority.High, type.Chore

#74 Modify Find feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/storemando/commons/core/Messages.java
  src/main/java/seedu/storemando/commons/util/StringUtil.java
  src/main/java/seedu/storemando/logic/commands/FindCommand.java
  src/main/java/seedu/storemando/logic/parser/FindCommandParser.java
  src/main/java/seedu/storemando/model/item/ItemNameContainsKeywordsPredicate.java
  src/main/java/seedu/storemando/model/item/NameContainsKeywordsPredicate.java
  src/test/java/seedu/storemando/commons/core/MessagesTest.java
  src/test/java/seedu/storemando/commons/util/StringUtilTest.java
  src/test/java/seedu/storemando/logic/commands/CommandTestUtil.java
  src/test/java/seedu/storemando/logic/commands/FindCommandTest.java
  src/test/java/seedu/storemando/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/StoreMandoParserTest.java
  src/test/java/seedu/storemando/model/ModelManagerTest.java
  src/test/java/seedu/storemando/model/item/ItemNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/storemando/model/item/NameContainsKeywordsPredicateTest.java
Labels: priority.High, severity.High, type.Story

#76 Modify Edit feature
  docs/UserGuide.md
  src/main/java/seedu/storemando/logic/commands/EditCommand.java
  src/main/java/seedu/storemando/logic/parser/CliSyntax.java
  src/main/java/seedu/storemando/logic/parser/EditCommandParser.java
  src/main/java/seedu/storemando/model/item/ExpiryDate.java
  src/main/java/seedu/storemando/model/item/Quantity.java
  src/main/java/seedu/storemando/model/util/SampleDataUtil.java
  src/main/java/seedu/storemando/storage/JsonAdaptedItem.java
  src/main/java/seedu/storemando/ui/ItemCard.java
  src/test/data/JsonSerializableStoreMandoTest/duplicateItemStoreMando.json
  src/test/data/JsonSerializableStoreMandoTest/invalidItemStoreMando.json
  src/test/data/JsonSerializableStoreMandoTest/typicalItemsStoreMando.json
  src/test/java/seedu/storemando/logic/commands/CommandTestUtil.java
  src/test/java/seedu/storemando/logic/commands/EditCommandTest.java
  src/test/java/seedu/storemando/logic/commands/FindCommandTest.java
  src/test/java/seedu/storemando/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/ParserUtilTest.java
  src/test/java/seedu/storemando/model/item/ExpiryDateTest.java
  src/test/java/seedu/storemando/model/item/ItemNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/storemando/model/item/ItemTest.java
  src/test/java/seedu/storemando/model/item/QuantityTest.java
  src/test/java/seedu/storemando/testutil/ItemBuilder.java
  src/test/java/seedu/storemando/testutil/ItemUtil.java
  src/test/java/seedu/storemando/testutil/TypicalItems.java
Labels: priority.High, severity.High, type.Story

#73 Modify List feature
  docs/UserGuide.md
  src/main/java/seedu/storemando/logic/commands/ListCommand.java
  src/main/java/seedu/storemando/logic/parser/ListCommandParser.java
  src/main/java/seedu/storemando/logic/parser/StoreMandoParser.java
  src/main/java/seedu/storemando/model/item/LocationContainsKeywordsPredicate.java
  src/test/java/seedu/storemando/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/storemando/model/item/LocationContainsKeywordsPredicateTest.java
Labels: priority.High, severity.High, type.Story

#75 Modify Add feature
  docs/UserGuide.md
  src/main/java/seedu/storemando/logic/commands/AddCommand.java
  src/main/java/seedu/storemando/logic/parser/AddCommandParser.java
  src/main/java/seedu/storemando/logic/parser/EditCommandParser.java
  src/main/java/seedu/storemando/model/item/ExpiryDate.java
  src/main/java/seedu/storemando/model/item/Item.java
  src/main/java/seedu/storemando/model/item/Quantity.java
  src/main/java/seedu/storemando/ui/ItemCard.java
  src/main/resources/view/ItemListCard.fxml
  src/test/java/seedu/storemando/logic/commands/AddCommandTest.java
  src/test/java/seedu/storemando/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/storemando/model/StoreMandoTest.java
  src/test/java/seedu/storemando/model/item/ExpiryDateTest.java
  src/test/java/seedu/storemando/model/item/ItemNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/storemando/model/item/ItemTest.java
  src/test/java/seedu/storemando/model/item/UniqueItemListTest.java
Labels: priority.High, severity.High, type.Story

#81 Modify Help feature
  src/main/java/seedu/storemando/ui/HelpWindow.java
Labels: priority.High, severity.Low, type.Chore

#83 Modify Delete feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, severity.VeryLow, type.Story

#79 Refactor docs
  README.md
  docs/DeveloperGuide.md
  docs/index.md
  docs/tutorials/AddRemark.md
Labels: priority.High, severity.VeryLow, type.Chore

#101 New Sort Feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/storemando/logic/commands/SortCommand.java
  src/main/java/seedu/storemando/logic/commands/SortExpiryDateCommand.java
  src/main/java/seedu/storemando/logic/commands/SortQuantityCommand.java
  src/main/java/seedu/storemando/logic/parser/SortCommandParser.java
  src/main/java/seedu/storemando/logic/parser/StoreMandoParser.java
  src/main/java/seedu/storemando/model/Model.java
  src/main/java/seedu/storemando/model/ModelManager.java
  src/main/java/seedu/storemando/model/item/ExpiryDate.java
  src/main/java/seedu/storemando/model/item/Item.java
  src/main/java/seedu/storemando/model/item/ItemComparatorByExpiryDate.java
  src/main/java/seedu/storemando/model/item/ItemComparatorByQuantity.java
  src/main/java/seedu/storemando/model/item/ItemName.java
  src/main/java/seedu/storemando/model/item/Location.java
  src/main/java/seedu/storemando/model/item/Quantity.java
  src/test/java/seedu/storemando/logic/commands/AddCommandTest.java
  src/test/java/seedu/storemando/logic/commands/CommandTestUtil.java
  src/test/java/seedu/storemando/logic/commands/SortExpiryDateCommandTest.java
  src/test/java/seedu/storemando/logic/commands/SortQuantityCommandTest.java
  src/test/java/seedu/storemando/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/StoreMandoParserTest.java
  src/test/java/seedu/storemando/testutil/TypicalItems.java
Labels: priority.Medium

#99 Edit message constraints
  src/main/java/seedu/storemando/logic/commands/AddCommand.java
  src/main/java/seedu/storemando/logic/commands/EditCommand.java
  src/main/java/seedu/storemando/model/item/ExpiryDate.java
  src/main/java/seedu/storemando/model/item/Item.java
  src/test/java/seedu/storemando/logic/commands/AddCommandTest.java
  src/test/java/seedu/storemando/logic/commands/CommandTestUtil.java
  src/test/java/seedu/storemando/logic/commands/EditCommandTest.java
  src/test/java/seedu/storemando/model/item/ExpiryDateTest.java
  src/test/java/seedu/storemando/model/item/ItemTest.java
  src/test/java/seedu/storemando/testutil/ItemBuilder.java
Labels: type.Chore, type.Enhancement

#100 Modify help feature to open user guide on browser
  docs/UserGuide.md
  src/main/java/seedu/storemando/commons/util/BrowserUtil.java
  src/main/java/seedu/storemando/logic/commands/HelpCommand.java
  src/main/java/seedu/storemando/ui/HelpWindow.java
  src/main/java/seedu/storemando/ui/MainWindow.java
Labels: priority.Medium, severity.Low, type.Enhancement

#93 Modify List feature v2
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/storemando/logic/commands/ListCommand.java
  src/main/java/seedu/storemando/logic/parser/ListCommandParser.java
  src/main/java/seedu/storemando/model/tag/TagContainsKeywordsPredicate.java
  src/test/java/seedu/storemando/logic/commands/CommandTestUtil.java
  src/test/java/seedu/storemando/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/StoreMandoParserTest.java
Labels: priority.Medium, severity.Medium, type.Story

#94 Remove tutorial folder
  docs/Configuration.md
  docs/DevOps.md
  docs/Documentation.md
  docs/SettingUp.md
  docs/Testing.md
  docs/UserGuide.md
  docs/index.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
Labels: priority.Medium, severity.VeryLow, type.Chore

#97 Change common variable names
  src/main/java/seedu/storemando/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableStoreMandoTest/duplicateItemStoreMando.json
  src/test/data/JsonSerializableStoreMandoTest/typicalItemsStoreMando.json
  src/test/java/seedu/storemando/logic/LogicManagerTest.java
  src/test/java/seedu/storemando/logic/commands/CommandTestUtil.java
  src/test/java/seedu/storemando/logic/commands/EditCommandTest.java
  src/test/java/seedu/storemando/logic/commands/EditItemDescriptorTest.java
  src/test/java/seedu/storemando/logic/commands/FindCommandTest.java
  src/test/java/seedu/storemando/logic/commands/SortExpiryDateCommandTest.java
  src/test/java/seedu/storemando/logic/commands/SortQuantityCommandTest.java
  src/test/java/seedu/storemando/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/storemando/model/ModelManagerTest.java
  src/test/java/seedu/storemando/model/StoreMandoTest.java
  src/test/java/seedu/storemando/model/item/ItemTest.java
  src/test/java/seedu/storemando/model/item/UniqueItemListTest.java
  src/test/java/seedu/storemando/storage/JsonAdaptedItemTest.java
  src/test/java/seedu/storemando/storage/JsonStoreMandoStorageTest.java
  src/test/java/seedu/storemando/testutil/TypicalItems.java
Labels: priority.Medium, type.Chore

#102 Basic update to GUI
  src/main/java/seedu/storemando/ui/ItemCard.java
  src/main/java/seedu/storemando/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/ItemListCard.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, severity.Low

#98 Add Feature reminder
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/storemando/commons/core/Messages.java
  src/main/java/seedu/storemando/logic/commands/ReminderCommand.java
  src/main/java/seedu/storemando/logic/parser/ReminderCommandParser.java
  src/main/java/seedu/storemando/logic/parser/StoreMandoParser.java
  src/main/java/seedu/storemando/model/item/ItemExpiringPredicate.java
  src/test/java/seedu/storemando/logic/commands/ReminderCommandTest.java
  src/test/java/seedu/storemando/logic/parser/ReminderCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/StoreMandoParserTest.java
  src/test/java/seedu/storemando/model/item/ItemExpiringPredicateTest.java
Labels: priority.High, severity.Medium, type.Story

#115 Modify Find feature v3
  src/main/java/seedu/storemando/logic/commands/FindCommand.java
Labels: priority.Medium, severity.Low, type.Enhancement

#116 Modify Clear feature
  src/main/java/seedu/storemando/logic/commands/ClearCommand.java
Labels: priority.Medium, severity.Low, type.Enhancement

#112 Move classes to new package
  src/main/java/seedu/storemando/commons/util/BrowserUtil.java
  src/main/java/seedu/storemando/logic/commands/EditCommand.java
  src/main/java/seedu/storemando/logic/commands/ReminderCommand.java
  src/main/java/seedu/storemando/logic/parser/AddCommandParser.java
  src/main/java/seedu/storemando/logic/parser/EditCommandParser.java
  src/main/java/seedu/storemando/logic/parser/ParserUtil.java
  src/main/java/seedu/storemando/logic/parser/ReminderCommandParser.java
  src/main/java/seedu/storemando/model/expirydate/ExpiryDate.java
  src/main/java/seedu/storemando/model/expirydate/ItemExpiringPredicate.java
  src/main/java/seedu/storemando/model/item/Item.java
  src/main/java/seedu/storemando/model/util/SampleDataUtil.java
  src/main/java/seedu/storemando/storage/JsonAdaptedItem.java
  src/main/java/seedu/storemando/ui/MainWindow.java
  src/main/resources/view/ItemListCard.fxml
  src/test/java/seedu/storemando/logic/commands/AddCommandTest.java
  src/test/java/seedu/storemando/logic/commands/ReminderCommandTest.java
  src/test/java/seedu/storemando/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/ParserUtilTest.java
  src/test/java/seedu/storemando/logic/parser/ReminderCommandParserTest.java
  src/test/java/seedu/storemando/model/item/ExpiryDateTest.java
  src/test/java/seedu/storemando/model/item/ItemExpiringPredicateTest.java
  src/test/java/seedu/storemando/storage/JsonAdaptedItemTest.java
  src/test/java/seedu/storemando/testutil/EditItemDescriptorBuilder.java
  src/test/java/seedu/storemando/testutil/ItemBuilder.java
  src/test/java/seedu/storemando/testutil/ItemUtil.java
Labels: priority.Medium, severity.Low, type.Chore

#119 Test full coverage
  src/test/java/seedu/storemando/model/item/ExpiryDateTest.java
  src/test/java/seedu/storemando/model/item/ItemComparatorByExpiryDateTest.java
  src/test/java/seedu/storemando/model/item/ItemComparatorByQuantityTest.java
  src/test/java/seedu/storemando/model/item/LocationTest.java
  src/test/java/seedu/storemando/model/item/NameTest.java
  src/test/java/seedu/storemando/model/item/QuantityTest.java
Labels: priority.High, severity.Low

#125 Update user guide
  docs/UserGuide.md
Labels: priority.High, severity.Low, type.Chore

#128 Update Kumaran markdown file
  docs/team/kumaran.md
Labels: priority.Medium, severity.VeryLow, type.Chore

#129 Update Fazil's markdown file
  docs/team/mohamedfazil.md
Labels: priority.Medium, severity.VeryLow, type.Chore

#130 Update Amanda's markdown file
  docs/team/amandaang.md
Labels: priority.Medium, severity.VeryLow, type.Chore

#120 Jay Markdown file
  build.gradle
  docs/team/jaychenyj.md
Labels: priority.High, severity.VeryLow, type.Chore

#126 Doc md weihao
  docs/team/chewwh09.md
Labels: priority.High, severity.VeryLow, type.Chore

#127 Feature edit v2
  src/main/java/seedu/storemando/logic/commands/EditCommand.java
  src/test/java/seedu/storemando/logic/commands/EditCommandTest.java
Labels: priority.Medium, severity.Low, type.Enhancement

#131 Feature reminder v2
  src/main/java/seedu/storemando/commons/core/Messages.java
  src/main/java/seedu/storemando/logic/commands/ReminderCommand.java
  src/main/java/seedu/storemando/logic/parser/ReminderCommandParser.java
  src/test/java/seedu/storemando/logic/commands/ReminderCommandTest.java
  src/test/java/seedu/storemando/logic/parser/ReminderCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/StoreMandoParserTest.java
Labels: priority.Medium, severity.High, type.Enhancement

#124 Update user guide
  docs/UserGuide.md
Labels: priority.High, severity.Low, type.Chore

#121 Update DG v2
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  docs/images/ArchitectureDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/johndoe.png
  docs/images/team-members/chewwh09.png
  docs/images/team-members/github-amanda.png
  docs/images/team-members/jaychenyj.png
  docs/images/team-members/kumsssss.png
  docs/images/team-members/md-fazil.png
  docs/team/johndoe.md
Labels: priority.High, severity.Low, type.Chore

#123 Feature gui v2
  src/main/java/seedu/storemando/logic/parser/ReminderCommandParser.java
  src/main/java/seedu/storemando/ui/ItemCard.java
  src/main/java/seedu/storemando/ui/MainWindow.java
  src/main/java/seedu/storemando/ui/ResultDisplay.java
  src/main/java/seedu/storemando/ui/StatusBarFooter.java
  src/main/java/seedu/storemando/ui/UiManager.java
  src/main/resources/images/calendar.png
  src/main/resources/images/clock.png
  src/main/resources/images/fail.png
  src/main/resources/images/info_icon.png
  src/main/resources/images/storemando_32.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/ItemListCard.fxml
  src/main/resources/view/MainTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/storemando/commons/util/AppUtilTest.java
Labels: priority.Medium, severity.Low, type.Chore

#145 Hotfix for v1.3.trail
  build.gradle
  src/main/java/seedu/storemando/MainApp.java
Labels: priority.High, severity.High, type.Bug

#142 add assertion for deleteCommandParser
  src/main/java/seedu/storemando/logic/parser/DeleteCommandParser.java
Labels: priority.High, severity.VeryLow, type.Chore

#147 Add assertion for quantity class
  src/main/java/seedu/storemando/model/item/Quantity.java
Labels: priority.High, severity.VeryLow, type.Chore

#140 Add assertions to ReminderCommandParser
  src/main/java/seedu/storemando/model/expirydate/ItemExpiringPredicate.java
  src/test/java/seedu/storemando/logic/commands/ReminderCommandTest.java
Labels: priority.High, severity.VeryLow, type.Chore

#152 Add assertion to ItemNameContainsPartialKeywordsPredicate class
  src/main/java/seedu/storemando/logic/commands/DeleteCommand.java
  src/main/java/seedu/storemando/logic/parser/AddCommandParser.java
  src/main/java/seedu/storemando/model/item/ItemNameContainsPartialKeywordsPredicate.java
Labels: priority.High, severity.Low, type.Chore

#153 Add one assertion in ItemNameContainsKeywordsPredicate
  src/main/java/seedu/storemando/model/item/ItemNameContainsKeywordsPredicate.java
  src/test/java/seedu/storemando/logic/commands/FindCommandTest.java
  src/test/java/seedu/storemando/model/item/ItemNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/storemando/model/item/ItemNameContainsPartialKeywordsPredicateTest.java
Labels: priority.High, severity.VeryLow, type.Chore

#141 Modify use case 6
  docs/DeveloperGuide.md
Labels: priority.High, severity.VeryLow, type.Story

#148 Add manual testing for add command in dg
  docs/DeveloperGuide.md
Labels: priority.High, severity.Low, type.Chore

#151 Add use case in DG
  docs/DeveloperGuide.md
Labels: priority.High, severity.Low, type.Chore

#143 Add use cases for sort feature
  docs/DeveloperGuide.md
Labels: priority.High, severity.Low, type.Chore

#156 Hotfix Team member photos
  docs/AboutUs.md
  docs/images/chewwh09.png
  docs/images/github-amanda.png
  docs/images/jaychenyj.png
  docs/images/kumsssss.png
  docs/images/md-fazil.png
Labels: priority.High, severity.Low

#155 Update DG v3
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Logging.md
  docs/SettingUp.md
  docs/Testing.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
Labels: priority.High, severity.Low, type.Chore

#167 Update tests in logic parser
  src/main/java/seedu/storemando/logic/parser/ListCommandParser.java
  src/test/java/seedu/storemando/logic/commands/CommandTestUtil.java
  src/test/java/seedu/storemando/logic/commands/EditCommandTest.java
  src/test/java/seedu/storemando/logic/commands/EditItemDescriptorTest.java
  src/test/java/seedu/storemando/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/storemando/model/StoreMandoTest.java
  src/test/java/seedu/storemando/model/item/ItemTest.java
  src/test/java/seedu/storemando/model/item/UniqueItemListTest.java
  src/test/java/seedu/storemando/testutil/TypicalItems.java
Labels: priority.High, severity.Low, type.Chore

#171 Modify Clear functionality and Sort functionality in UG
  docs/UserGuide.md
Labels: priority.Medium, severity.Low, type.Chore

#158 Update command on sublist
  src/main/java/seedu/storemando/logic/commands/FindCommand.java
  src/main/java/seedu/storemando/logic/commands/ListCommand.java
  src/main/java/seedu/storemando/logic/commands/ReminderCommand.java
  src/main/java/seedu/storemando/model/Model.java
  src/main/java/seedu/storemando/model/ModelManager.java
  src/test/java/seedu/storemando/logic/commands/AddCommandTest.java
Labels: priority.Medium, severity.Medium, type.Bug

#169 Update NFR, Glossary and Product Scope in DG
  docs/DeveloperGuide.md
Labels: priority.High, severity.Low, type.Chore

#160 Color coded the expiry date
  src/main/java/seedu/storemando/model/expirydate/ItemExpiringPredicate.java
  src/main/java/seedu/storemando/ui/ItemCard.java
  src/main/resources/view/ItemListCard.fxml
Labels: priority.Medium, severity.VeryLow, type.Enhancement

#174 Modify User Guide
  docs/UserGuide.md
Labels: priority.High, severity.High, type.Chore

#175 Update README, Index, UG
  README.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/index.md
Labels: priority.High, severity.Low, type.Chore

#178 Hotfix UG
  docs/UserGuide.md
Labels: priority.High, severity.Low, type.Bug

#173 Update Developer Guide
  docs/DeveloperGuide.md
Labels: priority.High, severity.Low, type.Chore

#168 Add tests for Model
  src/test/java/seedu/storemando/model/StoreMandoTest.java
  src/test/java/seedu/storemando/model/item/ExpiryDateTest.java
  src/test/java/seedu/storemando/model/item/ItemComparatorByDecreasingQuantityTest.java
  src/test/java/seedu/storemando/model/item/ItemExpiringPredicateTest.java
  src/test/java/seedu/storemando/model/item/ItemNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/storemando/model/item/ItemNameContainsPartialKeywordsPredicateTest.java
  src/test/java/seedu/storemando/model/item/ItemTest.java
  src/test/java/seedu/storemando/model/item/LocationTest.java
  src/test/java/seedu/storemando/model/item/NameTest.java
  src/test/java/seedu/storemando/model/item/QuantityTest.java
  src/test/java/seedu/storemando/model/tag/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/storemando/model/tag/TagTest.java
Labels: priority.Medium, severity.Low, type.Chore

#161 Add similar item warning for add and edit feature
  src/main/java/seedu/storemando/logic/commands/AddCommand.java
  src/main/java/seedu/storemando/logic/commands/EditCommand.java
  src/main/java/seedu/storemando/model/Model.java
  src/main/java/seedu/storemando/model/ModelManager.java
  src/main/java/seedu/storemando/model/StoreMando.java
  src/main/java/seedu/storemando/model/item/Item.java
  src/main/java/seedu/storemando/model/item/ItemName.java
  src/main/java/seedu/storemando/model/item/Location.java
  src/main/java/seedu/storemando/model/item/UniqueItemList.java
  src/test/java/seedu/storemando/logic/commands/AddCommandTest.java
  src/test/java/seedu/storemando/logic/commands/EditCommandTest.java
  src/test/java/seedu/storemando/model/ModelManagerTest.java
  src/test/java/seedu/storemando/model/StoreMandoTest.java
  src/test/java/seedu/storemando/model/item/ItemTest.java
  src/test/java/seedu/storemando/model/item/LocationTest.java
  src/test/java/seedu/storemando/model/item/NameTest.java
  src/test/java/seedu/storemando/model/item/UniqueItemListTest.java
  src/test/java/seedu/storemando/testutil/TypicalItems.java
Labels: priority.Medium, severity.VeryLow, type.Enhancement

#157 Reminder feature v4
  src/main/java/seedu/storemando/logic/commands/ReminderCommand.java
  src/main/java/seedu/storemando/logic/parser/ReminderCommandParser.java
  src/test/java/seedu/storemando/logic/commands/ReminderCommandTest.java
  src/test/java/seedu/storemando/logic/parser/ReminderCommandParserTest.java
Labels: priority.Medium, severity.Medium, type.Enhancement

#180 Update UG
  docs/UserGuide.md
Labels: priority.Medium, severity.Low, type.Chore

#181 Hotfix UG
  docs/UserGuide.md
Labels: priority.High, severity.Low, type.Bug

#179 Update UG and DG
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
Labels: priority.Medium, severity.Low, type.Chore

#182 Update Tests Logic Commands
  src/test/java/seedu/storemando/logic/commands/CommandResultTest.java
  src/test/java/seedu/storemando/logic/commands/FindCommandTest.java
  src/test/java/seedu/storemando/logic/commands/ListCommandTest.java
Labels: priority.Medium, severity.Low, type.Chore

#195 Hotfix large number exception
  src/main/java/seedu/storemando/model/item/Quantity.java
Labels: priority.High, severity.Low, type.Bug

#170 Modify feature clear by location
  src/main/java/seedu/storemando/logic/commands/ClearCommand.java
  src/main/java/seedu/storemando/logic/parser/ClearCommandParser.java
  src/main/java/seedu/storemando/logic/parser/StoreMandoParser.java
  src/main/java/seedu/storemando/model/Model.java
  src/main/java/seedu/storemando/model/ModelManager.java
  src/main/java/seedu/storemando/model/item/LocationContainsPredicate.java
  src/test/java/seedu/storemando/logic/commands/AddCommandTest.java
  src/test/java/seedu/storemando/logic/parser/ClearCommandParserTest.java
  src/test/java/seedu/storemando/logic/parser/StoreMandoParserTest.java
Labels: priority.Medium, severity.Medium, type.Story

#199 Hotfix Clear feature
  docs/UserGuide.md
  src/main/java/seedu/storemando/logic/commands/ClearCommand.java
Labels: priority.High, severity.High, type.Bug

#201 Update list feature
  src/main/java/seedu/storemando/commons/util/StringUtil.java
  src/main/java/seedu/storemando/model/item/LocationContainsKeywordsPredicate.java
  src/test/java/seedu/storemando/commons/util/StringUtilTest.java
  src/test/java/seedu/storemando/model/item/LocationContainsKeywordsPredicateTest.java
Labels: priority.High, severity.High, type.Bug

#206 UG v3 Jay
  docs/UserGuide.md
Labels: priority.High, severity.Medium, type.Chore

#208 Hotfix on UG v3 Jay
  docs/UserGuide.md
Labels: priority.High, severity.Medium, type.Bug

#209 Hotfix UG title
  docs/UserGuide.md
Labels: priority.High, severity.High, type.Bug
